### ISSUE TITLE
improper constraint error when specifying ">=version <version"

### ISSUE THREAD

**Issue by bleach** [cloudfoundry/nodejs-buildpack#95] opened 2017-07-18 15:35 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
api_version": "2.84.0"
cf version 6.23.1+a70deb38f.2017-01-13
```

## What version of the buildpack you are using?

v1.6.2

## If you were attempting to accomplish a task, what was it you were attempting to do?

Pushing https://github.com/alphagov/govuk_prototype_kit/ which has this node version specification in `package.json`

```
  "engines": {
    "node": ">=6.11.1 <7.0"
  },
```

## What did you expect to happen?

The app to be deployed with nodejs 6.11.1

Because [npm gives example ranges in its docs](https://docs.npmjs.com/misc/semver) that look like that

> For example, the range >=1.2.7 <1.3.0 would match the versions 1.2.7, 1.2.8, and 1.2.99, but not the versions 1.2.6, 1.3.0, or 1.1.0.

## What was the actual behavior?

`cf push` failed with this error:

```
-----> Installing binaries
       engines.node (package.json): >=6.11.1 <7.0
       engines.npm (package.json): unspecified (use default)
       **WARNING** Dangerous semver range (>) in engines.node. See: http://docs.cloudfoundry.org/buildpacks/node/node-tips.html
       **ERROR** Unable to install node: improper constraint: >=6.11.1 <7.0
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed
```

And then when I repeated this with `package.json` defined like this (adding a comma between the versions) it worked:

```
  "engines": {
    "node": ">=6.11.1, <7.0"
  },
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by bleach** [comment] 2017-07-18 16:24
I should have mentioned that this behaviour seems to have changed recently. It was working previously. We recently upgraded the nodejs buildpack to v1.6.2 from v1.5.31 and I suspect that broke it.

I think 1e084f41286c44c9ad0d70befb1af1adf226c5f9 may have caused it, as this now requires that the go semver library be happy with the version specification.

**Comment by sclevine** [comment] 2017-07-18 16:29
Thanks for the report! Looks like a regression to me. We'll cut a new release with a fix ASAP.

**Comment by sclevine** [comment] 2017-07-18 21:59
Fixed in [v1.6.3](https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.6.3).

(To maintain backwards compatibility, we fixed this by trying multiple different semver libraries sequentially until one doesn't fail to parse the version range. Node.js semver is awesome.)

**Closed by sclevine** 2017-07-18 21:59 UTC
Labels: accepted

**Comment by bleach** [comment] 2017-07-19 08:17
Many thanks for the rapid response to this!

**Comment by dotchev** [comment] 2017-08-07 09:06
you can do the same with
```json
  "engines": {
    "node": "^6.11.1"
  },
```
and it does work with Nodejs Buildpack version 1.6.2
