### ISSUE TITLE
sh: 1: prebuild: not found

### ISSUE THREAD

**Issue by charyorde** [cloudfoundry/nodejs-buildpack#68] opened 2016-10-14 13:13 UTC
What version of Cloud Foundry are you using?
235.5.73

What version of the buildpack you are using?
1.5.0

If you were attempting to accomplish a task, what was it you were attempting to do?
Push an app to CF

What did you expect to happen?

What was the actual behavior?
Staging...
-------> Buildpack version 1.5.0
-----> Creating runtime environment

```
   NPM_CONFIG_LOGLEVEL=error
   NPM_CONFIG_PRODUCTION=true
   NODE_MODULES_CACHE=true
```

-----> Installing binaries
       engines.node (package.json):  0.12.5
       engines.npm (package.json):   2.15.0

```
   Downloading and installing node 0.12.5...
   Downloading and installing npm 2.15.0 (replacing version 2.11.2)...
```

-----> Restoring cache
       Loading 1 from cacheDirectories (default):
       - node_modules (exists - skipping)
-----> Building dependencies
       Prebuild detected (node_modules already exists)
       Rebuilding any native modules

```
   > dtrace-provider@0.6.0 install /tmp/app/node_modules/cf-services-connector/node_modules/restify/node_modules/bunyan/node_modules/dtrace-provider
   > node scripts/install.js


   > dtrace-provider@0.3.2 install /tmp/app/node_modules/cf-services-connector/node_modules/restify/node_modules/dtrace-provider
   > node scripts/install.js


   > leveldown@1.4.6 install /tmp/app/node_modules/cf-services-connector/node_modules/level/node_modules/leveldown
   > prebuild --install

   sh: 1: prebuild: not found

   npm ERR! Linux 3.19.0-68-generic
   npm ERR! argv "node" "/tmp/app/.heroku/node/bin/npm" "rebuild"
   npm ERR! node v0.12.5  
   npm ERR! npm  v2.15.0  
   npm ERR! file sh
   npm ERR! code ELIFECYCLE
   npm ERR! errno ENOENT  
   npm ERR! syscall spawn 
   npm ERR! leveldown@1.4.6 install: `prebuild --install`
   npm ERR! spawn ENOENT  
   npm ERR!
   npm ERR! Failed at the leveldown@1.4.6 install script 'prebuild --install'.
```

I'm aware this is a leveldown issue. But a solution for it is to install `prebuild` like so `npm i prebuild`. How can I accomplish this?

Please confirm where necessary:
- [x ] I have included a log output 
- [x ] My log includes an error message 
- [ ] I have included steps for reproduction

**Comment by sesmith177** [comment] 2016-10-17 15:52
@charyorde it looks like you're using an old version of the buildpack (1.5.0). Could you try with the most recent release (1.5.21)?

Thanks.

**Comment by charyorde** [comment] 2016-10-17 17:10
@sesmith177 switched to `https://github.com/cloudfoundry/buildpack-nodejs.git#v1.5.21` in `manifest.yml`, but still got this:
```
> prebuild --install
       
       sh: 1: prebuild: not found
       
       npm ERR! Linux 3.19.0-69-generic
       npm ERR! argv "node" "/tmp/app/.heroku/node/bin/npm" "rebuild" "--nodedir=/tmp/app/.heroku/node"
       npm ERR! node v0.12.16
       npm ERR! npm  v2.15.0
       npm ERR! file sh
       npm ERR! code ELIFECYCLE
       npm ERR! errno ENOENT
       npm ERR! syscall spawn
       npm ERR! leveldown@1.4.6 install: `prebuild --install`
       npm ERR! spawn ENOENT
```

**Comment by sesmith177** [comment] 2016-10-17 18:05
@charyorde We have reproduced this issue and are looking in to it

**Comment by sesmith177** [comment] 2016-10-17 20:48
@charyorde The problem here is that the cf cli does not upload symlinks in the app directory (see issue: https://github.com/cloudfoundry/cli/issues/903).

So `node_modules/leveldown/node_modules/.bin/prebuild` (and any other symlinks in that directory) is not uploaded which causes `npm rebuild` to fail with the error you're seeing

**Comment by charyorde** [comment] 2016-10-17 20:54
Ah! That explains it. Thanks for digging into this. 

So is this a CF bug or I need to report this in the upstream project?

**Comment by sesmith177** [comment] 2016-10-18 14:18
@charyorde this is a CF bug; we've bumped the issue I linked above

**Comment by RochesterinNYC** [comment] 2016-10-31 14:02
@charyorde the CF CLI Team has prioritized a story investigating this symlink issue in their backlog: https://www.pivotaltracker.com/n/projects/892938/stories/79898768

**Comment by charyorde** [comment] 2016-10-31 14:25
Very good. Thank you.

**Comment by sesmith177** [comment] 2017-01-03 20:12
@charyorde since the discussion around this behavior has moved to a CF CLI issue (https://github.com/cloudfoundry/cli/issues/903) and [story](https://www.pivotaltracker.com/n/projects/892938/stories/79898768), we're going to close this issue for now.

Let us know if you have any questions.

**Closed by sesmith177** 2017-01-03 20:12 UTC
Labels: unscheduled
