### ISSUE TITLE
cross-env not found when trying to start application in PCF.

### ISSUE THREAD

**Issue by jndietz** [cloudfoundry/nodejs-buildpack#517] opened 2022-10-07 15:13 UTC
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**

`cf curl /v2/info`

```json
{
   "name": "VMware Tanzu Application Service",
   "build": "2.11.18-build.1",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-11/pcf-release-notes/runtime-rn.html",
   "authorization_endpoint": "https://login.sys.mycompany.com",
   "token_endpoint": "https://uaa.sys.mycompany.com",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "app_ssh_endpoint": "ssh.sys.mycompany.com:2222",
   "app_ssh_host_key_fingerprint": "79:46:fc:1e:50:90:e5:d5:27:b3:2c:c4:27:11:ad:9d",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.sys.mycompany.com:443",
   "api_version": "2.164.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.sys.mycompany.com/routing",
   "user": "72252b05-c2f7-4f35-a292-824ab0d366a7"
}
```

`cf version`

`cf version 7.3.0+645c3ce6a.2021-08-16`

**What version of the buildpack you are using?**

1.7.67

**If you were attempting to accomplish a task, what was it you were attempting to do?**

I was trying to start my application with the following command `cross-env NODE_ENV=development nest start`.  Manifest contents:

```yaml
---
---
applications:
  - name: my-app-d
    routes:
    - route: my-app-d.apps.mycompany
    command: cross-env NODE_ENV=development nest start
    buildpacks:
      - nodejs_buildpack
    instances: 1
    memory: 512MB
    health-check-type: http
    health-check-http-endpoint: /health
    env:
      NPM_CONFIG_REGISTRY: https://artifactory.mycompany/artifactory/api/npm/npm-mycompany
```

**What did you expect to happen?**

I expected the application to start successfully.

What was the actual behavior?

The log in PCF says...

```
2022-10-07T09:22:05.296-05:00 [APP/PROC/WEB/0] [OUT] > @my-app@1.0.0-9 start:dev
2022-10-07T09:22:05.296-05:00 [APP/PROC/WEB/0] [OUT] > cross-env NODE_ENV=development nest start --watch
2022-10-07T09:22:05.304-05:00 [APP/PROC/WEB/0] [ERR] sh: 1: cross-env: not found
2022-10-07T09:22:05.323-05:00 [APP/PROC/WEB/0] [OUT] Exit status 127
```

Can you provide a sample app?

Yes

**Workarounds**

I attempted to workaround this issue by doing something like this as the start command:

```
export PATH="$PATH:$(readlink -f node_modules/.bin/)" && npm run start:dev
```

But, I still see the same error:  `[ERR] sh: 1: cross-env: not found`

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by arjun024** [comment] 2022-10-25 08:10
I'm unable to reproduce the error.

Are you sure you're installing this external module named `cross-env` using `npm` or `yarn`?
For e.g. your `package.json` should have something like the following
```
‣ cat package.json | grep -A2 "dependencies"
  "dependencies": {
    "cross-env": "~7.0.3"
  }
```
The buildpack will use npm to install the dependency and thus the executable will be available to invocation at app start time.

If you have `cross-env` specified in your `package.json` and yet getting this error, please provide a sample application to reproduce the issue

**Comment by arjun024** [comment] 2022-10-28 04:16
Closing the issue. Feel free to reopen if you have added it to `package.json` and still running to issues

**Closed by arjun024** 2022-10-28 04:16 UTC
Labels: unscheduled
