### ISSUE TITLE
don't npm install in the cloud

### ISSUE THREAD

**Issue by dagda1** [cloudfoundry/nodejs-buildpack#152] opened 2018-07-25 13:38 UTC
is there anyway to not npm install on the cloud but instead just upload the node_modules from the deployment directory?

We have a private nexus and a yarn monorepo.  

I am currently using having to copy a `.yarnrc` file into the deployment directory that overrides the parent `.yarnrc` and looks like this:

```
registry "https://registry.yarnpkg.com"
yarn-offline-mirror "./npm-packages-offline-cache"
```

What I want to do is just push what I have in the directory and have full control of what is in the `node_modules` directory.

**Comment by mojjj** [comment] 2018-07-30 08:12
We have the same issue. our customer's private PCF platform has no internet access and we provide the node_modules along with the application.

a workaround is using binary packaging (using pkg modules), so the PCF does NOT use nodejs buildpack but the binary buildpack. 

however, we are now probably forced to use the nodejs buildpack again because we have a new dependency with AppDynamics. in discussion with the support of Appdynamics (https://community.appdynamics.com/t5/Dynamic-Languages-Node-JS-Python/Appdynamics-Protobuff-dependency-fails-due-to-invalid-tag-name/m-p/32376#M488), we foundnt he only solution is to fork the nodejs buildpack and remove the entries for "npm install" and "npm rebuild" 

having this as flagged option would be cool.

**Comment by dagda1** [comment] 2018-07-30 18:17
There are countless, [node-sass](https://github.com/sass/node-sass) being one, lots of npm modules have a post or prebuild that goes out to the internet. anything node-gyp can go out.

You cannot have caret dependencies with this model because they will be out of sync.  We also have an internal registry as I mentioned above which obviously the the ubuntu instance will not have access to. 

I have to have separate package.json and yarn.lock files to try and combat this.

I also have a yarn workspace monorepo which will have sym link dependencies.  I'd just like to just upload what I have like is possible with heroku.

**Comment by sclevine** [comment] 2018-08-06 22:44
If `node_modules` is properly vendored, the buildpack should only rebuild native extensions inside of the vendored `node_modules` directory. It should not cause npm to reach out to the internet. I think we agree on the intended behavior, assuming you agree that native extensions must be re-built for apps vendored on macOS or Windows to start successfully.

We'll attempt to replicate in case there's a regression, but I believe we have tests that cover this behavior.

**Comment by dagda1** [comment] 2018-08-09 18:09
You'd need to define properly vendored.  I use yarn and I had to go down the `npm-packages-offline-cache`.

It still did an npm install this way

**Comment by Ben16** [comment] 2018-08-10 14:25
Hi @dagda1! Are you using a yarn.lock file in your app? We use the [presence/absence of a `yarn.lock`](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/src/nodejs/supply/supply.go#L300) to determine whether to build with yarn or npm. We'll make sure to update [our documentation](https://docs.cloudfoundry.org/buildpacks/node/index.html) to reflect this.
If you do have a `yarn.lock` and are still seeing an npm install, then there is clearly an issue and we'd be happy to look into it further. If that's the case, could you provide us with a sample app so we can replicate the behavior?

**Comment by OmidH** [comment] 2018-08-15 08:46
@Ben16 Yes, please add it to your documentation. This is an important peace of information.
> You can use Yarn as an alternative that verifies dependencies.
isn't just enough!

**Comment by astrieanna** [comment] 2018-08-15 13:52
@OmidH we are updating the docs https://github.com/cloudfoundry/docs-buildpacks/pull/212

**Comment by tylerphelan** [comment] 2018-08-31 19:16
Closing this issue as it seems to be resolved. Please open it again if you have problems again.

**Closed by tylerphelan** 2018-08-31 19:16 UTC
Labels: unscheduled
